apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-tingesopep2
  labels:
    app: postgres-tingesopep2
spec:
  selector:
    matchLabels:
      app: postgres-tingesopep2
  template:
    metadata:
      labels:
        app: postgres-tingesopep2
    spec:
      containers:
        - name: postgres-tingesopep2
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "tingeso"
          volumeMounts:
            - name: postgres-tingesopep2-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-tingesopep2-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-tingesopep2-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-tingesopep2-pv-claim
  labels:
    app: postgres-tingesopep2
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-tingesopep2
  labels:
    app: postgres-tingesopep2
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-tingesopep2
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tingesopep2
data:
  name: "tingeso"

---
