server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service.default.svc.cluster.local:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: acopio-service
          uri: lb://acopio-service
          predicates:
            - Path=/acopio/**
        - id: nutricional-service
          uri: lb://nutricional-service
          predicates:
            - Path=/nutricional/**
        - id: pago-service
          uri: lb://pago-service
          predicates:
            - Path=/pago/**
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/proveedor/**