server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service.default.svc.cluster.local:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: acopio-service
          uri: lb://acopio-service
          predicates:
            - Path=/acopios/**
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/proveedores/**
        - id: nutricional-service
          uri: lb://nutricional-service
          predicates:
            - Path=/nutricionales/**
        - id: pago-service
          uri: lb://pago-service
          predicates:
            - Path=/pagos/**
